// Canonical 66-book Protestant order. `slug` is the filename in the upstream
// TehShrike/world-english-bible repo; `id` is the stable 3-letter code used in
// verse reference keys (BOOK.CHAPTER.VERSE) everywhere else in the app.
export const BOOKS = [
  { id: 'GEN', name: 'Genesis',         testament: 'OT', slug: 'genesis' },
  { id: 'EXO', name: 'Exodus',          testament: 'OT', slug: 'exodus' },
  { id: 'LEV', name: 'Leviticus',       testament: 'OT', slug: 'leviticus' },
  { id: 'NUM', name: 'Numbers',         testament: 'OT', slug: 'numbers' },
  { id: 'DEU', name: 'Deuteronomy',     testament: 'OT', slug: 'deuteronomy' },
  { id: 'JOS', name: 'Joshua',          testament: 'OT', slug: 'joshua' },
  { id: 'JDG', name: 'Judges',          testament: 'OT', slug: 'judges' },
  { id: 'RUT', name: 'Ruth',            testament: 'OT', slug: 'ruth' },
  { id: '1SA', name: '1 Samuel',        testament: 'OT', slug: '1samuel' },
  { id: '2SA', name: '2 Samuel',        testament: 'OT', slug: '2samuel' },
  { id: '1KI', name: '1 Kings',         testament: 'OT', slug: '1kings' },
  { id: '2KI', name: '2 Kings',         testament: 'OT', slug: '2kings' },
  { id: '1CH', name: '1 Chronicles',    testament: 'OT', slug: '1chronicles' },
  { id: '2CH', name: '2 Chronicles',    testament: 'OT', slug: '2chronicles' },
  { id: 'EZR', name: 'Ezra',            testament: 'OT', slug: 'ezra' },
  { id: 'NEH', name: 'Nehemiah',        testament: 'OT', slug: 'nehemiah' },
  { id: 'EST', name: 'Esther',          testament: 'OT', slug: 'esther' },
  { id: 'JOB', name: 'Job',             testament: 'OT', slug: 'job' },
  { id: 'PSA', name: 'Psalms',          testament: 'OT', slug: 'psalms' },
  { id: 'PRO', name: 'Proverbs',        testament: 'OT', slug: 'proverbs' },
  { id: 'ECC', name: 'Ecclesiastes',    testament: 'OT', slug: 'ecclesiastes' },
  { id: 'SNG', name: 'Song of Solomon', testament: 'OT', slug: 'songofsolomon' },
  { id: 'ISA', name: 'Isaiah',          testament: 'OT', slug: 'isaiah' },
  { id: 'JER', name: 'Jeremiah',        testament: 'OT', slug: 'jeremiah' },
  { id: 'LAM', name: 'Lamentations',    testament: 'OT', slug: 'lamentations' },
  { id: 'EZK', name: 'Ezekiel',         testament: 'OT', slug: 'ezekiel' },
  { id: 'DAN', name: 'Daniel',          testament: 'OT', slug: 'daniel' },
  { id: 'HOS', name: 'Hosea',           testament: 'OT', slug: 'hosea' },
  { id: 'JOL', name: 'Joel',            testament: 'OT', slug: 'joel' },
  { id: 'AMO', name: 'Amos',            testament: 'OT', slug: 'amos' },
  { id: 'OBA', name: 'Obadiah',         testament: 'OT', slug: 'obadiah' },
  { id: 'JON', name: 'Jonah',           testament: 'OT', slug: 'jonah' },
  { id: 'MIC', name: 'Micah',           testament: 'OT', slug: 'micah' },
  { id: 'NAM', name: 'Nahum',           testament: 'OT', slug: 'nahum' },
  { id: 'HAB', name: 'Habakkuk',        testament: 'OT', slug: 'habakkuk' },
  { id: 'ZEP', name: 'Zephaniah',       testament: 'OT', slug: 'zephaniah' },
  { id: 'HAG', name: 'Haggai',          testament: 'OT', slug: 'haggai' },
  { id: 'ZEC', name: 'Zechariah',       testament: 'OT', slug: 'zechariah' },
  { id: 'MAL', name: 'Malachi',         testament: 'OT', slug: 'malachi' },
  { id: 'MAT', name: 'Matthew',         testament: 'NT', slug: 'matthew' },
  { id: 'MRK', name: 'Mark',            testament: 'NT', slug: 'mark' },
  { id: 'LUK', name: 'Luke',            testament: 'NT', slug: 'luke' },
  { id: 'JHN', name: 'John',            testament: 'NT', slug: 'john' },
  { id: 'ACT', name: 'Acts',            testament: 'NT', slug: 'acts' },
  { id: 'ROM', name: 'Romans',          testament: 'NT', slug: 'romans' },
  { id: '1CO', name: '1 Corinthians',   testament: 'NT', slug: '1corinthians' },
  { id: '2CO', name: '2 Corinthians',   testament: 'NT', slug: '2corinthians' },
  { id: 'GAL', name: 'Galatians',       testament: 'NT', slug: 'galatians' },
  { id: 'EPH', name: 'Ephesians',       testament: 'NT', slug: 'ephesians' },
  { id: 'PHP', name: 'Philippians',     testament: 'NT', slug: 'philippians' },
  { id: 'COL', name: 'Colossians',      testament: 'NT', slug: 'colossians' },
  { id: '1TH', name: '1 Thessalonians', testament: 'NT', slug: '1thessalonians' },
  { id: '2TH', name: '2 Thessalonians', testament: 'NT', slug: '2thessalonians' },
  { id: '1TI', name: '1 Timothy',       testament: 'NT', slug: '1timothy' },
  { id: '2TI', name: '2 Timothy',       testament: 'NT', slug: '2timothy' },
  { id: 'TIT', name: 'Titus',           testament: 'NT', slug: 'titus' },
  { id: 'PHM', name: 'Philemon',        testament: 'NT', slug: 'philemon' },
  { id: 'HEB', name: 'Hebrews',         testament: 'NT', slug: 'hebrews' },
  { id: 'JAS', name: 'James',           testament: 'NT', slug: 'james' },
  { id: '1PE', name: '1 Peter',         testament: 'NT', slug: '1peter' },
  { id: '2PE', name: '2 Peter',         testament: 'NT', slug: '2peter' },
  { id: '1JN', name: '1 John',          testament: 'NT', slug: '1john' },
  { id: '2JN', name: '2 John',          testament: 'NT', slug: '2john' },
  { id: '3JN', name: '3 John',          testament: 'NT', slug: '3john' },
  { id: 'JUD', name: 'Jude',            testament: 'NT', slug: 'jude' },
  { id: 'REV', name: 'Revelation',      testament: 'NT', slug: 'revelation' },
]
