import React, { useState } from 'react'
import type { ResearchProject, ResearchCapsule } from '../../../../shared/research/types'
import { buildResearchCapsule, type CapsuleSelection } from '../../../../shared/research/capsule'
import ResearchDialog from './ResearchDialog'
export default function CapsulePreview({ project, onClose, onExport, privateWindow = false }: { project: ResearchProject; onClose: () => void; onExport: (capsule: ResearchCapsule) => Promise<void> | void; privateWindow?: boolean }) {
  const [selection, setSelection] = useState<CapsuleSelection>({ claimIds: project.claims.map(c => c.id), sourceIds: project.sources.map(s => s.id), claimText: {}, sourceUrls: {}, quotes: {} })
  const [busy, setBusy] = useState(false), [error, setError] = useState('')
  const result = buildResearchCapsule(project, selection)
  const toggle = (key: 'claimIds' | 'sourceIds', id: string) => setSelection(s => ({ ...s, [key]: s[key].includes(id) ? s[key].filter(x => x !== id) : [...s[key], id] }))
  return <ResearchDialog title="Preview research capsule" onClose={() => { if (!busy) onClose() }}><p>Review everything below before sharing. The ZIP contains an offline report and importable JSON. Full page text, private notes and AI settings are omitted.</p>{privateWindow && <p className="research-badge review">Export saves private-window research outside this session. The file remains after you close the window.</p>}<p className="research-muted">Links may reveal signed-in page addresses. Remove URLs and edit quotes manually; automatic redaction is not guaranteed.</p><h3>{project.title}</h3><p>{project.question}</p>{project.claims.map(c => <section className="research-card" key={c.id}><label><input type="checkbox" checked={selection.claimIds.includes(c.id)} onChange={() => toggle('claimIds', c.id)} /> Include finding</label><textarea aria-label="Shared finding" maxLength={2000} value={selection.claimText[c.id] ?? c.text} onChange={e => setSelection(s => ({ ...s, claimText: { ...s.claimText, [c.id]: e.target.value } }))} />{c.citations.map((q, i) => <label key={i}>Shared quote<textarea maxLength={4000} value={selection.quotes[`${c.id}:${i}`] ?? q.quote} onChange={e => setSelection(s => ({ ...s, quotes: { ...s.quotes, [`${c.id}:${i}`]: e.target.value } }))} /></label>)}</section>)}{project.sources.map(s => <section className="research-card" key={s.id}><label><input type="checkbox" checked={selection.sourceIds.includes(s.id)} onChange={() => toggle('sourceIds', s.id)} /> Include source: {s.title}</label><input aria-label={`Shared URL for ${s.title}`} placeholder="Omit original URL" value={selection.sourceUrls[s.id] === null ? '' : selection.sourceUrls[s.id] ?? s.url ?? ''} maxLength={2048} onChange={e => setSelection(v => ({ ...v, sourceUrls: { ...v.sourceUrls, [s.id]: e.target.value || null } }))} /><small>Captured {s.capturedAt} · shared excerpts only</small>{result.ok && result.value.sources.find(x => x.id === s.id)?.excerpts.map((q, i) => <blockquote key={i}>{q}</blockquote>)}</section>)}<p className="research-muted">Edited or missing evidence can leave findings marked Needs review.</p>{(!result.ok || error) && <p role="alert">{!result.ok ? result.error : error}</p>}<div className="research-actions"><button onClick={onClose} disabled={busy}>Cancel</button><button className="primary" data-export disabled={!result.ok || busy} onClick={async () => { if (!result.ok) return; setBusy(true); try { await onExport(result.value) } catch (e) { setError(e instanceof Error ? e.message : 'Export failed.') } finally { setBusy(false) } }}>{busy ? 'Exporting…' : 'Export capsule'}</button></div></ResearchDialog>
}
